before_install:
  - gem update bundler rake
branches:
  only:
    - master
cache: bundler
env:
  global:
    secure: | # CODECLIMATE_REPO_TOKEN
      c1IvkNUiB8/23zmAof8gkthrz79Iou+e/rKddC6w11CNwv0s5nusWgjtwuMg
      fEEfEFU+Q3TPDtZ+YUjXbzRST6w734OqEltU0QNoFd+j1PL94c6o8iEniJT+
      JAhKTfB5G7X8ZApxCSwBg3ADhM5VdNbF1itYQkg4OJac2mQfx38=
gemfile:
  - gemfiles/active_record/5-0.gemfile
  - gemfiles/active_record/5-1.gemfile
  - gemfiles/active_record/5-2.gemfile
  - gemfiles/mongo_mapper/0-14.gemfile
  - gemfiles/mongo_mapper/0-15.gemfile
  - gemfiles/mongoid/6-4.gemfile
  - gemfiles/mongoid/7-1.gemfile
  - gemfiles/mongoid/7-1.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
  # exclude:
  #   - rvm: 2.6.5
  #     gemfile: gemfiles/active_record/5-1.gemfile
  #   - rvm: 2.6.5
  #     gemfile: gemfiles/active_record/5-2.gemfile
rvm:
  - 2.6.5
  - ruby-head
script: bundle exec rspec
services: mongodb
sudo: false
